name: infocep
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  flutter_spinkit: ^5.1.0
  sembast: ^3.3.0
  path: ^1.8.2
  path_provider: ^2.0.11
  advance_notification: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
