name: infocep
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  flutter_spinkit: ^5.1.0
  sembast: ^3.3.0
  path: ^1.8.2
  path_provider: ^2.0.11
  http: ^0.13.5
  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  intl: ^0.17.0
  sweetsheet: ^0.4.0
  pagination_view: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
